// Auth
export const LOGIN_SCREEN = 'LOGIN_SCREEN';
export const REGISTER_SCREEN = 'REGISTER_SCREEN';
export const FORGOT_PASSWORD_SCREEN = 'FORGOT_PASSWORD_SCREEN';
export const VERIFY_EMAIL_SCREEN = 'VERIFY_EMAIL_SCREEN';
export const VERIFY_OTP_SCREEN = 'VERIFY_OTP_SCREEN';

// Home & Content
export const HOME_SCREEN = 'HOME_SCREEN';
export const READING_SCREEN = 'READING_SCREEN';
export const STREAKS_SCREEN = 'STREAKS_SCREEN';
export const LESSON_OVERVIEW_SCREEN = 'LESSON_OVERVIEW_SCREEN';

// Quiz
export const QUIZ_SCREEN = 'QUIZ_SCREEN';
export const QUIZZES_LIST_SCREEN = 'QUIZZES_LIST_SCREEN';

// Monetization
export const PAYWALL_SCREEN = 'PAYWALL_SCREEN';
export const WINBACK_PAYWALL_SCREEN = 'WINBACK_PAYWALL_SCREEN';

// Other
export const SPLASH_SCREEN = 'SPLASH_SCREEN';
export const SELECT_LANGUAGE_SCREEN = 'SELECT_LANGUAGE_SCREEN';
